services:
  - type: web
    name: alshifa-herb-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SUPABASE_URL
        value: https://nbbkbsdikayrdocvpmea.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iYmtic2Rpa2F5cmRvY3ZwbWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyNDMwMjEsImV4cCI6MjA5ODgxOTAyMX0.t5EV8_mahMxP2VDYoFmv1sgW3RYjxeUlQkqbN9EHd2U
      - key: OPENWA_URL
        value: https://wa.prime-store.in
      - key: OPENWA_TOKEN
        value: owa_k1_1f9fc33877c037ca05d671dfa6159b7cba01eb7e00114694adc94dc675bacdb5
      - key: OPENWA_SESSION
        value: 1807ae98-6886-42bb-8584-690cbb79b2e0
      - key: ADMIN_PHONE
        value: 9119084044
      - key: ITL_ACCESS_TOKEN
        value: c1e9d8b5bb18c2888c9fa0a791881a37
      - key: ITL_SECRET_KEY
        value: 43333376b9f770b5f2007100cf4d4f3c
      - key: ITL_PICKUP_ADDRESS_ID
        value: 119045
      - key: ITL_RETURN_ADDRESS_ID
        value: 119045
      - key: SITE_URL
        value: https://tariq0840.github.io/al-shifa-herb
